### PR TITLE
Fixes #202

### LINKED ISSUE #202: viewer fails to visualize mulitple elements
## problem description
I want to visualize the following model. 
```xml
<?xml version="1.0" ?>
<robot name="myrobot">
   <link name="base_link">
      <visual>
         <geometry>
            <box size="0.5 0.5 0.1"/>
         </geometry>
         <origin rpy="0.0 -0.0 0.0" xyz="0.0 0.0 0.0"/>
      </visual>
      <visual>
         <geometry>
            <box size="0.5 0.5 0.1"/>
         </geometry>
         <origin rpy="0.0 -0.0 0.0" xyz="0.0 0.0 1.0"/>
      </visual>
   </link>
</robot>
```
where the model is consists of two box with 1m distance.  Let me call above xml file as `test.xml` then I tried to visualize it by the following code: 
```python
import skrobot
robot = skrobot.models.urdf.RobotModelFromURDF(urdf_file="./test.xml")
link = robot.base_link
viewer = skrobot.viewers.TrimeshSceneViewer(resolution=(640, 480))
viewer.add(robot)
viewer.show()
```
However, the result was like the image below, which shows that only single elements is visualized. 
 

## problem is not in loading multiple urdf mesh
I firstly thought that there is a bug while loading urdf link that has multiple visual elements, but found that there is no such bag by the following trial in interpreter. The result shows that the two visual element is properly loaded and passed to the trimesh scene. Also, we can confirm that two visual elements has 1m distance each other. (see the z component of the vertices).
```bash
In [2]: viewer.scene.geometry
Out[2]: 
OrderedDict([('140623407120144',
              <trimesh.Trimesh(vertices.shape=(8, 3), faces.shape=(12, 3))>),
             (u'140623407120144:IDQCEYQX9PJF',
              <trimesh.Trimesh(vertices.shape=(8, 3), faces.shape=(12, 3))>)])
In [4]: viewer.scene.geometry.values()[0].vertices
Out[4]: 
TrackedArray([[-0.25, -0.25, -0.05],
              [-0.25, -0.25,  0.05],
              [-0.25,  0.25, -0.05],
              [-0.25,  0.25,  0.05],
              [ 0.25, -0.25, -0.05],
              [ 0.25, -0.25,  0.05],
              [ 0.25,  0.25, -0.05],
              [ 0.25,  0.25,  0.05]])
In [5]: viewer.scene.geometry.values()[1].vertices
Out[5]: 
TrackedArray([[-0.25, -0.25,  0.95],
              [-0.25, -0.25,  1.05],
              [-0.25,  0.25,  0.95],
              [-0.25,  0.25,  1.05],
              [ 0.25, -0.25,  0.95],
              [ 0.25, -0.25,  1.05],
              [ 0.25,  0.25,  0.95],
              [ 0.25,  0.25,  1.05]])
```

## problem seems not in trimesh side
Next I thought it might be a problem in the trimesh side. So, I tried the following snippets to check it, which directly corresponding the geometries of the above metioned xml file. 
```python
import skrobot
import trimesh
import trimesh.viewer
import numpy as np

robot = skrobot.models.urdf.RobotModelFromURDF(urdf_file="./test.xml")
link = robot.base_link
mesh_list = link.visual_mesh
scene = trimesh.Scene()
scene.add_geometry(mesh_list)
scene.show()
```
The result was the following, which successfully show the two boxes and implies bug is not in the trimesh side.

### PR DESCRIPTION
**Pull request by iory**
Fixed visualization for multiple meshes

### CODE REVIEW

**Comment by iory** [comment]
@HiroIshida Please check this PR.

**Comment by HiroIshida** [comment]
Thanks for fixing this! the TODO means that probably the problem is in the trimesh side?

**Comment by iory** [comment]
Yes. add_geometry function's behavior causes this problem.
https://github.com/mikedh/trimesh/blob/master/trimesh/scene/scene.py#L127-L134

**Comment by HiroIshida** [comment]
I understand

**Pull request merged**
